#pragma once

#include <iostream>
#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <string.h>
#include <string>
#include <sys/select.h>
#include <signal.h>
#include <sstream>
#include <map>
#include <fcntl.h>
#include <netinet/in.h>
#include <cstdlib>
#include <exception>
#include <cstring>
#include <stdio.h>
#include <poll.h>
#include <vector>
#include <map>
#include <sstream>
